const { withAppBuildGradle } = require("@expo/config-plugins");

/**
 * Sign release builds with the real upload key instead of the debug key.
 *
 * Google Play rejects debug-signed builds outright, and `android/` is both
 * gitignored and regenerated by `expo prebuild` — so editing build.gradle by
 * hand loses the signing config the next time anyone prebuilds. This plugin
 * re-applies it every time, which is what makes the release reproducible.
 *
 * The credentials are NOT in this repo (it is public). They are read from
 * Gradle properties, which live in the user-level ~/.gradle/gradle.properties:
 *
 *   JAMIN_STORE_FILE=C:/Users/.../jamin-bazaar-release.jks
 *   JAMIN_STORE_PASSWORD=...
 *   JAMIN_KEY_ALIAS=jamin-bazaar
 *   JAMIN_KEY_PASSWORD=...
 *
 * If those properties are absent the release build falls back to the debug
 * signing config, exactly as before — so a fresh clone still builds and runs,
 * it just produces something that cannot be uploaded to Play. That fallback is
 * deliberate: a missing key should not break the build for everyone else.
 */
const SIGNING_CONFIG = `
        release {
            if (project.hasProperty('JAMIN_STORE_FILE')) {
                storeFile file(JAMIN_STORE_FILE)
                storePassword JAMIN_STORE_PASSWORD
                keyAlias JAMIN_KEY_ALIAS
                keyPassword JAMIN_KEY_PASSWORD
            }
        }`;

function addSigningConfig(src) {
  if (src.includes("JAMIN_STORE_FILE")) return src; // already applied
  // insert a `release {...}` block alongside the generated `debug {...}` one
  return src.replace(
    /signingConfigs\s*\{/,
    (match) => `${match}${SIGNING_CONFIG}`
  );
}

function useReleaseSigning(src) {
  // The generated release buildType points at signingConfigs.debug. Point it at
  // the release config when the key is available, else leave it alone.
  if (src.includes("signingConfig signingConfigs.release")) return src;
  return src.replace(
    /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
    `$1signingConfig project.hasProperty('JAMIN_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`
  );
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") return cfg;
    let src = cfg.modResults.contents;
    src = addSigningConfig(src);
    src = useReleaseSigning(src);
    cfg.modResults.contents = src;
    return cfg;
  });
};
