const { withAndroidManifest } = require("@expo/config-plugins");

/**
 * Declare the apps we deep-link into, so Android can actually find them.
 *
 * Android 11 (API 30) filters package visibility: an app only sees the
 * packages it declares in <queries>, plus the ones matching a declared intent.
 * That filtering applies to implicit intent RESOLUTION too, not just to
 * queryIntentActivities — so `Linking.openURL("instagram://app")` threw
 * ActivityNotFoundException on phones that had Instagram installed, and the
 * Referral Centre reported "Instagram isn't installed" (owner bug report
 * 07-08 #7).
 *
 * Expo's generated manifest already carries the <queries> block for https and
 * for the intents its own modules need; this appends the custom-scheme entries
 * on top. `android/` is gitignored and regenerated by `expo prebuild`, so this
 * has to be a plugin — a hand-edited manifest would be lost on the next
 * prebuild, exactly as documented in withReleaseSigning.js.
 *
 * Nothing here grants a permission or changes behaviour when the app is
 * absent: an undeclared package is invisible, a declared one that is not
 * installed simply still fails to resolve, and the caller's catch handles it.
 */

/** Packages we launch by their own URL scheme. */
const PACKAGES = [
  // Referral Centre → "Instagram" share tile (instagram://app).
  "com.instagram.android",
];

/** Schemes we send people to, so ACTION_VIEW/SENDTO can be resolved. */
const SCHEMES = ["instagram", "smsto", "sms", "tel", "mailto"];

module.exports = function withAndroidQueries(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;

    // Expo may or may not have created the block already — reuse it if so,
    // because a second <queries> element is invalid.
    if (!Array.isArray(manifest.queries)) manifest.queries = [];
    if (manifest.queries.length === 0) manifest.queries.push({});
    const queries = manifest.queries[0];

    if (!Array.isArray(queries.package)) queries.package = [];
    for (const name of PACKAGES) {
      const already = queries.package.some((p) => p?.$?.["android:name"] === name);
      if (!already) queries.package.push({ $: { "android:name": name } });
    }

    if (!Array.isArray(queries.intent)) queries.intent = [];
    for (const scheme of SCHEMES) {
      const already = queries.intent.some((i) =>
        (i?.data ?? []).some((d) => d?.$?.["android:scheme"] === scheme)
      );
      if (already) continue;
      queries.intent.push({
        action: [{ $: { "android:name": "android.intent.action.VIEW" } }],
        data: [{ $: { "android:scheme": scheme } }],
      });
    }

    return cfg;
  });
};
