-- 0067: Brochure cover image.
--
-- The brochure was offered as a bare link. People do not tap a bare link to a
-- 5.9 MB file they cannot see, so the app now shows the brochure's own first
-- page as a thumbnail before opening it.
--
-- Nullable: with no cover the app falls back to the property's first photo,
-- so this can never make the brochure unreachable.
alter table public.properties add column if not exists brochure_cover_url text;

comment on column public.properties.brochure_cover_url is
  'Thumbnail shown before opening the brochure — normally page 1 of the PDF, '
  'generated by the admin console. Falls back to the first property photo.';
